version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://server:3001

  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app 
